spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://svc.sel3.cloudtype.app:30403/officefinder
    username: root
    password: root

  jwt:
    secret: emVyb2Jhc2Utc3ByaW5nLWJvb3QtYXNzaWdubWVudC1kYXRhLXdpdGgtand0LXNlY3JldC1rZXk=
    token-header: "Authorization"
    token-prefix: "Bearer "

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  redis:
    host: localhost
    port: 6379
    password: dev

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  oauth2:
    google:
      client-id: 767358295321-d9akkeh90t0u2uakttjah33qvplpgtru.apps.googleusercontent.com
      client-secret: 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
      redirect-uri: http://localhost:8080/login/oauth2/code/google
      token-uri: https://oauth2.googleapis.com/token
      resource-uri: https://www.googleapis.com/oauth2/v2/userinfo

logging:
  level:
    org.hibernate.SQL: debug
